// Wardrobe System for Pockets
// Each slot can be customized independently

export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary'
export type SlotType = 'hat' | 'shirt' | 'pants' | 'shoes' | 'accessory'

export interface WardrobeItem {
  id: string
  name: string
  slot: SlotType
  rarity: Rarity
  emoji: string // For UI display
  description: string
  unlockMethod: 'default' | 'purchase' | 'achievement' | 'event' | 'level'
  price?: number // In crumbs
  requiredLevel?: number
  requiredAchievement?: string
  colors: string[] // Available color options
  zIndex: number // Layer order for rendering
}

export interface PlayerOutfit {
  hat: string | null
  shirt: string | null
  pants: string | null
  shoes: string | null
  accessory: string | null
}

export const RARITY_CONFIG: Record<Rarity, { color: string; bgColor: string; label: string; glow: string }> = {
  common: { color: '#9ca3af', bgColor: 'bg-gray-500/20', label: 'Common', glow: '' },
  uncommon: { color: '#22c55e', bgColor: 'bg-green-500/20', label: 'Uncommon', glow: 'shadow-green-500/30' },
  rare: { color: '#3b82f6', bgColor: 'bg-blue-500/20', label: 'Rare', glow: 'shadow-blue-500/30' },
  epic: { color: '#a855f7', bgColor: 'bg-purple-500/20', label: 'Epic', glow: 'shadow-purple-500/50' },
  legendary: { color: '#f59e0b', bgColor: 'bg-yellow-500/20', label: 'Legendary', glow: 'shadow-yellow-500/50' },
}

// ==========================================
// HATS
// ==========================================
export const HATS: WardrobeItem[] = [
  // Common Hats
  {
    id: 'hat_none',
    name: 'No Hat',
    slot: 'hat',
    rarity: 'common',
    emoji: '❌',
    description: 'Au naturel',
    unlockMethod: 'default',
    colors: [],
    zIndex: 50,
  },
  {
    id: 'hat_beanie',
    name: 'Cozy Beanie',
    slot: 'hat',
    rarity: 'common',
    emoji: '🧢',
    description: 'A warm knit beanie',
    unlockMethod: 'default',
    colors: ['#ef4444', '#3b82f6', '#22c55e', '#000000'],
    zIndex: 50,
  },
  {
    id: 'hat_cap',
    name: 'Baseball Cap',
    slot: 'hat',
    rarity: 'common',
    emoji: '🧢',
    description: 'Classic snapback style',
    unlockMethod: 'purchase',
    price: 100,
    colors: ['#ef4444', '#3b82f6', '#000000', '#ffffff'],
    zIndex: 50,
  },
  // Uncommon Hats
  {
    id: 'hat_cowboy',
    name: 'Cowboy Hat',
    slot: 'hat',
    rarity: 'uncommon',
    emoji: '🤠',
    description: 'Yeehaw partner!',
    unlockMethod: 'purchase',
    price: 250,
    colors: ['#92400e', '#000000', '#fef3c7'],
    zIndex: 50,
  },
  {
    id: 'hat_hockey_helmet',
    name: 'Hockey Helmet',
    slot: 'hat',
    rarity: 'uncommon',
    emoji: '🏒',
    description: 'Protect that noggin',
    unlockMethod: 'purchase',
    price: 300,
    colors: ['#000000', '#ffffff', '#ef4444', '#3b82f6'],
    zIndex: 50,
  },
  {
    id: 'hat_chef',
    name: 'Chef Hat',
    slot: 'hat',
    rarity: 'uncommon',
    emoji: '👨‍🍳',
    description: 'The master of treats',
    unlockMethod: 'achievement',
    requiredAchievement: 'collect_1000_treats',
    colors: ['#ffffff'],
    zIndex: 50,
  },
  // Rare Hats
  {
    id: 'hat_crown',
    name: 'Royal Crown',
    slot: 'hat',
    rarity: 'rare',
    emoji: '👑',
    description: 'For the treat royalty',
    unlockMethod: 'purchase',
    price: 750,
    colors: ['#fbbf24', '#c0c0c0', '#b45309'],
    zIndex: 50,
  },
  {
    id: 'hat_tophat',
    name: 'Top Hat',
    slot: 'hat',
    rarity: 'rare',
    emoji: '🎩',
    description: 'Fancy and sophisticated',
    unlockMethod: 'purchase',
    price: 600,
    colors: ['#000000', '#1f2937', '#4b5563'],
    zIndex: 50,
  },
  {
    id: 'hat_headphones',
    name: 'DJ Headphones',
    slot: 'hat',
    rarity: 'rare',
    emoji: '🎧',
    description: 'Drop the beet!',
    unlockMethod: 'purchase',
    price: 500,
    colors: ['#000000', '#ef4444', '#22c55e', '#8b5cf6'],
    zIndex: 50,
  },
  // Epic Hats
  {
    id: 'hat_astronaut',
    name: 'Astronaut Helmet',
    slot: 'hat',
    rarity: 'epic',
    emoji: '👨‍🚀',
    description: 'One small step for Pockets...',
    unlockMethod: 'purchase',
    price: 1500,
    colors: ['#ffffff', '#f59e0b'],
    zIndex: 50,
  },
  {
    id: 'hat_viking',
    name: 'Viking Helmet',
    slot: 'hat',
    rarity: 'epic',
    emoji: '⚔️',
    description: 'Raid the pantry!',
    unlockMethod: 'achievement',
    requiredAchievement: 'defeat_all_bosses',
    colors: ['#78716c', '#fbbf24'],
    zIndex: 50,
  },
  // Legendary Hats
  {
    id: 'hat_santa',
    name: 'Santa Hat',
    slot: 'hat',
    rarity: 'legendary',
    emoji: '🎅',
    description: 'Ho ho ho! The original Pockets look',
    unlockMethod: 'event',
    colors: ['#dc2626', '#ffffff'],
    zIndex: 50,
  },
  {
    id: 'hat_halo',
    name: 'Golden Halo',
    slot: 'hat',
    rarity: 'legendary',
    emoji: '😇',
    description: 'Angelic treat thief',
    unlockMethod: 'achievement',
    requiredAchievement: 'perfect_all_levels',
    colors: ['#fbbf24'],
    zIndex: 50,
  },
]

// ==========================================
// SHIRTS
// ==========================================
export const SHIRTS: WardrobeItem[] = [
  // Common Shirts
  {
    id: 'shirt_none',
    name: 'No Shirt',
    slot: 'shirt',
    rarity: 'common',
    emoji: '❌',
    description: 'Just fur',
    unlockMethod: 'default',
    colors: [],
    zIndex: 30,
  },
  {
    id: 'shirt_tee',
    name: 'Basic Tee',
    slot: 'shirt',
    rarity: 'common',
    emoji: '👕',
    description: 'Simple and comfy',
    unlockMethod: 'default',
    colors: ['#ffffff', '#000000', '#ef4444', '#3b82f6', '#22c55e', '#fbbf24'],
    zIndex: 30,
  },
  {
    id: 'shirt_striped',
    name: 'Striped Shirt',
    slot: 'shirt',
    rarity: 'common',
    emoji: '👕',
    description: 'Classic stripes',
    unlockMethod: 'purchase',
    price: 75,
    colors: ['#1e3a8a', '#991b1b', '#166534'],
    zIndex: 30,
  },
  // Uncommon Shirts
  {
    id: 'shirt_hoodie',
    name: 'Cozy Hoodie',
    slot: 'shirt',
    rarity: 'uncommon',
    emoji: '🧥',
    description: 'Warm and stylish',
    unlockMethod: 'purchase',
    price: 200,
    colors: ['#6b7280', '#3b82f6', '#ef4444', '#8b5cf6', '#000000'],
    zIndex: 30,
  },
  {
    id: 'shirt_basketball',
    name: 'Basketball Jersey',
    slot: 'shirt',
    rarity: 'uncommon',
    emoji: '🏀',
    description: 'Baller status',
    unlockMethod: 'purchase',
    price: 300,
    colors: ['#7c3aed', '#f59e0b', '#dc2626', '#22c55e'],
    zIndex: 30,
  },
  {
    id: 'shirt_hockey',
    name: 'Hockey Jersey',
    slot: 'shirt',
    rarity: 'uncommon',
    emoji: '🏒',
    description: 'Ready for the ice',
    unlockMethod: 'purchase',
    price: 350,
    colors: ['#000000', '#dc2626', '#3b82f6', '#ffffff'],
    zIndex: 30,
  },
  {
    id: 'shirt_flannel',
    name: 'Hipster Flannel',
    slot: 'shirt',
    rarity: 'uncommon',
    emoji: '🪵',
    description: 'Artisanal treat hunting',
    unlockMethod: 'purchase',
    price: 250,
    colors: ['#dc2626', '#22c55e', '#3b82f6'],
    zIndex: 30,
  },
  // Rare Shirts
  {
    id: 'shirt_suit_jacket',
    name: 'Suit Jacket',
    slot: 'shirt',
    rarity: 'rare',
    emoji: '🤵',
    description: 'Dapper raccoon',
    unlockMethod: 'purchase',
    price: 600,
    colors: ['#000000', '#1e3a8a', '#4b5563'],
    zIndex: 30,
  },
  {
    id: 'shirt_leather',
    name: 'Leather Jacket',
    slot: 'shirt',
    rarity: 'rare',
    emoji: '🧥',
    description: 'Too cool for school',
    unlockMethod: 'purchase',
    price: 550,
    colors: ['#000000', '#78350f'],
    zIndex: 30,
  },
  {
    id: 'shirt_snowsuit_top',
    name: 'Snowsuit Top',
    slot: 'shirt',
    rarity: 'rare',
    emoji: '❄️',
    description: 'Warm and puffy',
    unlockMethod: 'purchase',
    price: 500,
    colors: ['#dc2626', '#3b82f6', '#22c55e', '#ffffff'],
    zIndex: 30,
  },
  // Epic Shirts
  {
    id: 'shirt_superhero',
    name: 'Superhero Suit',
    slot: 'shirt',
    rarity: 'epic',
    emoji: '🦸',
    description: 'With great treats comes great responsibility',
    unlockMethod: 'purchase',
    price: 1200,
    colors: ['#dc2626', '#3b82f6', '#000000'],
    zIndex: 30,
  },
  {
    id: 'shirt_tuxedo',
    name: 'Tuxedo Shirt',
    slot: 'shirt',
    rarity: 'epic',
    emoji: '🎭',
    description: 'Black tie treat affair',
    unlockMethod: 'purchase',
    price: 1000,
    colors: ['#ffffff'],
    zIndex: 30,
  },
  // Legendary Shirts
  {
    id: 'shirt_santa_coat',
    name: 'Santa Coat',
    slot: 'shirt',
    rarity: 'legendary',
    emoji: '🎅',
    description: 'The classic look',
    unlockMethod: 'event',
    colors: ['#dc2626'],
    zIndex: 30,
  },
  {
    id: 'shirt_galaxy',
    name: 'Galaxy Hoodie',
    slot: 'shirt',
    rarity: 'legendary',
    emoji: '🌌',
    description: 'Cosmic treat hunter',
    unlockMethod: 'achievement',
    requiredAchievement: 'reach_1000m_runner',
    colors: ['#4c1d95'],
    zIndex: 30,
  },
]

// ==========================================
// PANTS
// ==========================================
export const PANTS: WardrobeItem[] = [
  // Common Pants
  {
    id: 'pants_none',
    name: 'No Pants',
    slot: 'pants',
    rarity: 'common',
    emoji: '❌',
    description: 'Natural raccoon style',
    unlockMethod: 'default',
    colors: [],
    zIndex: 20,
  },
  {
    id: 'pants_jeans',
    name: 'Classic Jeans',
    slot: 'pants',
    rarity: 'common',
    emoji: '👖',
    description: 'Reliable denim',
    unlockMethod: 'default',
    colors: ['#1e3a8a', '#000000', '#6b7280'],
    zIndex: 20,
  },
  {
    id: 'pants_shorts',
    name: 'Casual Shorts',
    slot: 'pants',
    rarity: 'common',
    emoji: '🩳',
    description: 'Cool and breezy',
    unlockMethod: 'purchase',
    price: 50,
    colors: ['#1e3a8a', '#000000', '#ca8a04', '#dc2626'],
    zIndex: 20,
  },
  // Uncommon Pants
  {
    id: 'pants_joggers',
    name: 'Sport Joggers',
    slot: 'pants',
    rarity: 'uncommon',
    emoji: '🏃',
    description: 'Athletic and comfy',
    unlockMethod: 'purchase',
    price: 200,
    colors: ['#000000', '#6b7280', '#1e3a8a'],
    zIndex: 20,
  },
  {
    id: 'pants_basketball',
    name: 'Basketball Shorts',
    slot: 'pants',
    rarity: 'uncommon',
    emoji: '🏀',
    description: 'Game ready',
    unlockMethod: 'purchase',
    price: 250,
    colors: ['#7c3aed', '#f59e0b', '#dc2626', '#22c55e'],
    zIndex: 20,
  },
  {
    id: 'pants_cargo',
    name: 'Cargo Pants',
    slot: 'pants',
    rarity: 'uncommon',
    emoji: '👖',
    description: 'Extra pockets for extra treats!',
    unlockMethod: 'purchase',
    price: 275,
    colors: ['#78716c', '#365314', '#78350f'],
    zIndex: 20,
  },
  // Rare Pants
  {
    id: 'pants_suit',
    name: 'Suit Pants',
    slot: 'pants',
    rarity: 'rare',
    emoji: '👔',
    description: 'Professional vibes',
    unlockMethod: 'purchase',
    price: 500,
    colors: ['#000000', '#1e3a8a', '#4b5563'],
    zIndex: 20,
  },
  {
    id: 'pants_snowsuit',
    name: 'Snow Pants',
    slot: 'pants',
    rarity: 'rare',
    emoji: '❄️',
    description: 'Insulated and warm',
    unlockMethod: 'purchase',
    price: 450,
    colors: ['#dc2626', '#3b82f6', '#22c55e', '#000000'],
    zIndex: 20,
  },
  {
    id: 'pants_ripped',
    name: 'Ripped Jeans',
    slot: 'pants',
    rarity: 'rare',
    emoji: '👖',
    description: 'Stylishly distressed',
    unlockMethod: 'purchase',
    price: 400,
    colors: ['#1e3a8a', '#000000'],
    zIndex: 20,
  },
  // Epic Pants
  {
    id: 'pants_tuxedo',
    name: 'Tuxedo Pants',
    slot: 'pants',
    rarity: 'epic',
    emoji: '🎭',
    description: 'With satin stripe',
    unlockMethod: 'purchase',
    price: 900,
    colors: ['#000000'],
    zIndex: 20,
  },
  {
    id: 'pants_superhero',
    name: 'Hero Tights',
    slot: 'pants',
    rarity: 'epic',
    emoji: '🦸',
    description: 'Aerodynamic!',
    unlockMethod: 'purchase',
    price: 850,
    colors: ['#dc2626', '#3b82f6', '#000000'],
    zIndex: 20,
  },
  // Legendary Pants
  {
    id: 'pants_santa',
    name: 'Santa Pants',
    slot: 'pants',
    rarity: 'legendary',
    emoji: '🎅',
    description: 'Red velvet classic',
    unlockMethod: 'event',
    colors: ['#dc2626'],
    zIndex: 20,
  },
]

// ==========================================
// SHOES
// ==========================================
export const SHOES: WardrobeItem[] = [
  // Common Shoes
  {
    id: 'shoes_none',
    name: 'Bare Paws',
    slot: 'shoes',
    rarity: 'common',
    emoji: '🐾',
    description: 'Natural grip',
    unlockMethod: 'default',
    colors: [],
    zIndex: 10,
  },
  {
    id: 'shoes_sneakers',
    name: 'Classic Sneakers',
    slot: 'shoes',
    rarity: 'common',
    emoji: '👟',
    description: 'Everyday kicks',
    unlockMethod: 'default',
    colors: ['#ffffff', '#000000', '#dc2626', '#3b82f6'],
    zIndex: 10,
  },
  {
    id: 'shoes_sandals',
    name: 'Summer Sandals',
    slot: 'shoes',
    rarity: 'common',
    emoji: '🩴',
    description: 'Beach vibes',
    unlockMethod: 'purchase',
    price: 75,
    colors: ['#78350f', '#000000', '#3b82f6'],
    zIndex: 10,
  },
  // Uncommon Shoes
  {
    id: 'shoes_hightops',
    name: 'High Tops',
    slot: 'shoes',
    rarity: 'uncommon',
    emoji: '👟',
    description: 'Street style',
    unlockMethod: 'purchase',
    price: 225,
    colors: ['#000000', '#ffffff', '#dc2626', '#22c55e'],
    zIndex: 10,
  },
  {
    id: 'shoes_basketball',
    name: 'Basketball Shoes',
    slot: 'shoes',
    rarity: 'uncommon',
    emoji: '🏀',
    description: 'Air Pockets',
    unlockMethod: 'purchase',
    price: 300,
    colors: ['#dc2626', '#000000', '#ffffff', '#f59e0b'],
    zIndex: 10,
  },
  {
    id: 'shoes_boots',
    name: 'Work Boots',
    slot: 'shoes',
    rarity: 'uncommon',
    emoji: '🥾',
    description: 'Tough and rugged',
    unlockMethod: 'purchase',
    price: 250,
    colors: ['#78350f', '#000000', '#78716c'],
    zIndex: 10,
  },
  // Rare Shoes
  {
    id: 'shoes_skates',
    name: 'Ice Skates',
    slot: 'shoes',
    rarity: 'rare',
    emoji: '⛸️',
    description: 'Glide through levels',
    unlockMethod: 'purchase',
    price: 550,
    colors: ['#ffffff', '#000000'],
    zIndex: 10,
  },
  {
    id: 'shoes_dress',
    name: 'Dress Shoes',
    slot: 'shoes',
    rarity: 'rare',
    emoji: '👞',
    description: 'Polished perfection',
    unlockMethod: 'purchase',
    price: 500,
    colors: ['#000000', '#78350f'],
    zIndex: 10,
  },
  {
    id: 'shoes_snow',
    name: 'Snow Boots',
    slot: 'shoes',
    rarity: 'rare',
    emoji: '❄️',
    description: 'Warm and waterproof',
    unlockMethod: 'purchase',
    price: 475,
    colors: ['#000000', '#78350f', '#dc2626'],
    zIndex: 10,
  },
  // Epic Shoes
  {
    id: 'shoes_rocket',
    name: 'Rocket Boots',
    slot: 'shoes',
    rarity: 'epic',
    emoji: '🚀',
    description: 'Blast off!',
    unlockMethod: 'purchase',
    price: 1100,
    colors: ['#dc2626', '#f59e0b'],
    zIndex: 10,
  },
  {
    id: 'shoes_golden',
    name: 'Golden Kicks',
    slot: 'shoes',
    rarity: 'epic',
    emoji: '✨',
    description: 'Dripping in gold',
    unlockMethod: 'achievement',
    requiredAchievement: 'collect_100_golden',
    colors: ['#fbbf24'],
    zIndex: 10,
  },
  // Legendary Shoes
  {
    id: 'shoes_santa_boots',
    name: 'Santa Boots',
    slot: 'shoes',
    rarity: 'legendary',
    emoji: '🎅',
    description: 'Black and shiny',
    unlockMethod: 'event',
    colors: ['#000000'],
    zIndex: 10,
  },
  {
    id: 'shoes_rainbow',
    name: 'Rainbow Runners',
    slot: 'shoes',
    rarity: 'legendary',
    emoji: '🌈',
    description: 'Leave a trail of color',
    unlockMethod: 'achievement',
    requiredAchievement: 'complete_all_worlds',
    colors: ['#ec4899'],
    zIndex: 10,
  },
]

// ==========================================
// ACCESSORIES
// ==========================================
export const ACCESSORIES: WardrobeItem[] = [
  // Common Accessories
  {
    id: 'acc_none',
    name: 'No Accessory',
    slot: 'accessory',
    rarity: 'common',
    emoji: '❌',
    description: 'Keep it simple',
    unlockMethod: 'default',
    colors: [],
    zIndex: 40,
  },
  {
    id: 'acc_glasses',
    name: 'Cool Shades',
    slot: 'accessory',
    rarity: 'common',
    emoji: '😎',
    description: 'Too cool',
    unlockMethod: 'purchase',
    price: 100,
    colors: ['#000000', '#78350f', '#3b82f6'],
    zIndex: 40,
  },
  // Uncommon Accessories
  {
    id: 'acc_necklace',
    name: 'Gold Chain',
    slot: 'accessory',
    rarity: 'uncommon',
    emoji: '📿',
    description: 'Bling bling',
    unlockMethod: 'purchase',
    price: 350,
    colors: ['#fbbf24', '#c0c0c0'],
    zIndex: 40,
  },
  {
    id: 'acc_bowtie',
    name: 'Bow Tie',
    slot: 'accessory',
    rarity: 'uncommon',
    emoji: '🎀',
    description: 'Dapper touch',
    unlockMethod: 'purchase',
    price: 200,
    colors: ['#000000', '#dc2626', '#3b82f6', '#22c55e'],
    zIndex: 40,
  },
  {
    id: 'acc_scarf',
    name: 'Cozy Scarf',
    slot: 'accessory',
    rarity: 'uncommon',
    emoji: '🧣',
    description: 'Warm and fashionable',
    unlockMethod: 'purchase',
    price: 225,
    colors: ['#dc2626', '#3b82f6', '#22c55e', '#fbbf24'],
    zIndex: 40,
  },
  // Rare Accessories
  {
    id: 'acc_cape',
    name: 'Hero Cape',
    slot: 'accessory',
    rarity: 'rare',
    emoji: '🦸',
    description: 'Flowing behind you',
    unlockMethod: 'purchase',
    price: 600,
    colors: ['#dc2626', '#3b82f6', '#8b5cf6', '#000000'],
    zIndex: 5, // Behind body
  },
  {
    id: 'acc_backpack',
    name: 'Treat Backpack',
    slot: 'accessory',
    rarity: 'rare',
    emoji: '🎒',
    description: 'Extra storage',
    unlockMethod: 'purchase',
    price: 500,
    colors: ['#dc2626', '#3b82f6', '#22c55e', '#f59e0b'],
    zIndex: 5,
  },
  // Epic Accessories
  {
    id: 'acc_wings',
    name: 'Angel Wings',
    slot: 'accessory',
    rarity: 'epic',
    emoji: '👼',
    description: 'Heavenly',
    unlockMethod: 'purchase',
    price: 1500,
    colors: ['#ffffff', '#fbbf24'],
    zIndex: 5,
  },
  {
    id: 'acc_monocle',
    name: 'Fancy Monocle',
    slot: 'accessory',
    rarity: 'epic',
    emoji: '🧐',
    description: 'Sophisticated sight',
    unlockMethod: 'achievement',
    requiredAchievement: 'defeat_baron',
    colors: ['#fbbf24'],
    zIndex: 40,
  },
  // Legendary Accessories
  {
    id: 'acc_santa_bag',
    name: 'Santa\'s Bag',
    slot: 'accessory',
    rarity: 'legendary',
    emoji: '🎁',
    description: 'Filled with presents',
    unlockMethod: 'event',
    colors: ['#dc2626'],
    zIndex: 5,
  },
  {
    id: 'acc_aura',
    name: 'Champion Aura',
    slot: 'accessory',
    rarity: 'legendary',
    emoji: '✨',
    description: 'Glowing with power',
    unlockMethod: 'achievement',
    requiredAchievement: 'top_10_leaderboard',
    colors: ['#fbbf24', '#8b5cf6', '#ec4899'],
    zIndex: 60,
  },
]

// All items combined
export const ALL_WARDROBE_ITEMS: WardrobeItem[] = [
  ...HATS,
  ...SHIRTS,
  ...PANTS,
  ...SHOES,
  ...ACCESSORIES,
]

// Get items by slot
export const getItemsBySlot = (slot: SlotType): WardrobeItem[] => {
  return ALL_WARDROBE_ITEMS.filter(item => item.slot === slot)
}

// Get item by ID
export const getItemById = (id: string): WardrobeItem | undefined => {
  return ALL_WARDROBE_ITEMS.find(item => item.id === id)
}

// Default outfit
export const DEFAULT_OUTFIT: PlayerOutfit = {
  hat: 'hat_none',
  shirt: 'shirt_none',
  pants: 'pants_none',
  shoes: 'shoes_none',
  accessory: 'acc_none',
}

// Complete outfit sets (for quick equip)
export const OUTFIT_SETS = [
  {
    id: 'set_santa',
    name: 'Santa Pockets',
    description: 'The classic Christmas look',
    rarity: 'legendary' as Rarity,
    items: {
      hat: 'hat_santa',
      shirt: 'shirt_santa_coat',
      pants: 'pants_santa',
      shoes: 'shoes_santa_boots',
      accessory: 'acc_santa_bag',
    },
  },
  {
    id: 'set_basketball',
    name: 'Baller',
    description: 'Ready for the court',
    rarity: 'uncommon' as Rarity,
    items: {
      hat: 'hat_cap',
      shirt: 'shirt_basketball',
      pants: 'pants_basketball',
      shoes: 'shoes_basketball',
      accessory: 'acc_necklace',
    },
  },
  {
    id: 'set_tuxedo',
    name: 'Black Tie',
    description: 'Formal treat hunting',
    rarity: 'epic' as Rarity,
    items: {
      hat: 'hat_tophat',
      shirt: 'shirt_tuxedo',
      pants: 'pants_tuxedo',
      shoes: 'shoes_dress',
      accessory: 'acc_bowtie',
    },
  },
  {
    id: 'set_snowsuit',
    name: 'Snow Day',
    description: 'Winter ready',
    rarity: 'rare' as Rarity,
    items: {
      hat: 'hat_beanie',
      shirt: 'shirt_snowsuit_top',
      pants: 'pants_snowsuit',
      shoes: 'shoes_snow',
      accessory: 'acc_scarf',
    },
  },
  {
    id: 'set_hipster',
    name: 'Hipster',
    description: 'Artisanal vibes',
    rarity: 'uncommon' as Rarity,
    items: {
      hat: 'hat_beanie',
      shirt: 'shirt_flannel',
      pants: 'pants_ripped',
      shoes: 'shoes_boots',
      accessory: 'acc_glasses',
    },
  },
  {
    id: 'set_superhero',
    name: 'Super Pockets',
    description: 'Saving treats everywhere',
    rarity: 'epic' as Rarity,
    items: {
      hat: 'hat_none',
      shirt: 'shirt_superhero',
      pants: 'pants_superhero',
      shoes: 'shoes_rocket',
      accessory: 'acc_cape',
    },
  },
]
